name: dio_authentication_client
description: A Very Good Project created by Very Good CLI.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  rxdart: ^0.27.7
  token_storage:
    path: ../token_storage

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
