name: user_repository
description: A Very Good Project created by Very Good CLI.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  equatable: ^2.0.5
  qwerty_api_client:
    path: ../qwerty_api_client/qwerty_api_client

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
