version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/storage/storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/storage/secure_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/qwerty_api_client/qwerty_api_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/qwerty_api_client/dio_qwerty_api_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/app_ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/form_inputs"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/authentication_client/authentication_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/authentication_client/dio_authentication_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/authentication_client/token_storage"
    schedule:
      interval: "daily"