name: secure_storage
description: A Very Good Project created by Very Good CLI.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_secure_storage: ^8.0.0
  storage:
    path: ../storage

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
