name: dio_qwerty_api_client
description: A Very Good Project created by Very Good CLI.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.2.1+1
  qwerty_api_client:
    path: ../qwerty_api_client

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
