name: form_inputs
description: A Very Good Project created by Very Good CLI.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
dependencies:
  formz: ^0.6.0
